### ISSUE TITLE
Metro_1

### ISSUE THREAD

**Issue by smyilik** [smyilik/WASP_Homeworks#1]
@vdetstvepil 
Я почти сделал Метро 1, но я не понимаю, что нужно сделать в последнем методе класса Metro(void LoadStationsFromFile(string filename)). Я бы понял, если бы это было в классе Line, но в Metro же нам нужно создать Line и положить уже внутри Line эти станции из файла в список stations, но тогда где мы берём характеристики ветки(name, color), и то на сколько веток должны разделиться эти станции из файла или все станции принадлежать лишь одной ветке.
А ещё я закоментил неработающие методы, у меня код не компилируется так как я незнаю, что нужно возвращать в методах (Line.FindStationByName (string name), metro.FindStation (string name), metro.FindStation(string name, string lineName), metro.GetStationList(string name)) если в списке нет элемента, удовлетворяющего условиям. В школе нас обычно просят возвращать -1 или "-1" в таких ситуациях, в зависимости от типа функции, но тут метод, тип данных которого не позволяет так сделать. Компилятор пишет, что не все пути ведут к return'у, не смотря на то что это у меня происходит только если пользователь не введёт все нужные данные.
p.s. Было бы неплохо если бы вы поясняли, что нужно сделать в самых сложных функциях/методах, если такие имеются. И автоматические checker это круто и удобно, так сразу понятно, что правильно, а что нет.
Извиняюсь за такое длинное сообщение, я наверное побил все рекорды по объёму такого рода сообщений

**Comment by vdetstvepil** [comment]
А метод LoadStationsFromFile нужно будет реализовать во второй части задания :) поспешил немножко.
В методах, которые ты перечислил, нужно возвращать пустую ссылку - null. В методе GetStation или FindStationByName (это два дубликата) следует организовать цикл foreach, который будет проходить по списку объектов класса Station, брать имя этого объекта и сравнивать с искомым именем. Если ничего не найдется, то возвращаем пустую ссылку.

**Файл Station.cs**
- 26 строка. Если присвоишь один список другому, то элементы из второго списка не перепрыгнут в первый. Знаком равно ты просто присваиваешь первому списку ссылку на второй список. Если у тебя второй список поменяется, удалится и т.п., изменения в первом списке проявятся немедленно. Как избежать: просто через цикл foreach добавить элементы из второго списка в основной список. Или воспользоваться функцией AddRange.

**Comment by vdetstvepil** [comment]
Если будут вопросы, напиши в личку. Авансом ставлю фулл балл, только поправь закоментированные методы.
