### ISSUE TITLE
Autopark

### ISSUE THREAD

**Issue by smyilik** [smyilik/WASP_Homeworks#2]
@vdetstvepil

**Comment by vdetstvepil** [comment]
- 11 строка. А почему в конструктор не поступают новые переменные в качестве параметров?
- 20 строка. Аналогично.
- 49 строка. Аналогично.
- 76 строка. Класс AutoPark объявлен внутри класса Truck. Это не логично; наверное, случайность.
- 79-80 строка. Объявлять поля нужно в этом месте, а вот инициализировать их следует в конструкторе. Это будет корректнее.
- 81 строка. Конструктор без модификатора, а модификатор по умолчанию у нас private. Таким образом, если мы захотим создать объект AutoPark, то у нас ничего не выйдет, ибо доступ к конструктору нам заказан.
- 39 и 72 строка. Нужно переопределить метод ToString(), а ты написал свой метод. Это делается так: public override string ToString() { }

**Comment by vdetstvepil** [comment]
Исправишь косяки, тогда зачту.

**Comment by smyilik** [comment]
@vdetstvepil
Я исправил, но вылезает предупреждение, что нужно чтобы метод Car.ToString() предоставлял реализацию и для этого нужно добавить ключевое слово override, не смотря на то, что я его добавил. Я посмотрел в интернете и на записи, либо я что-то не заметил, либо это какая-то ошибка VS. Метод всё равно работает и код компилируется

**Comment by vdetstvepil** [comment]
Наверное, баг. Всё правильно сделал, молодец 👍 Принято.
