### ISSUE TITLE
Audio disks store

### ISSUE THREAD

**Issue by smyilik** [smyilik/WASP_Homeworks#3]
@vdetstvepil 
У меня почему-то переменные типа DVD не работают со списками, поэтому я закомментировал 166-170, 194-203, 213-215, 222-225 строки, в них находится код того, как бы я это реализовал если бы у меня работали переменные типа DVD со списками

**Comment by vdetstvepil** [comment]
Потому что у тебя модификатор доступности класса DVD не public. Если допишешь public, все будет работать.

**Comment by vdetstvepil** [comment]
Принято (вместе с доп. заданием).
