### ISSUE TITLE
WPF дз 1

### ISSUE THREAD

**Issue by smyilik** [smyilik/WASP_Homeworks#5]
@GalteXx выложил, только я не понял как сделать масштабирование нормальное, как у калькулятора в винде, поэтому сделал так, а ещё хотел сделать, чтобы когда наводишь на passwordbox у тебя курсор появлялся в конце набора символов, но тоже не понял как

**Comment by GalteXx** [comment]
Запомни эти вопросы, до следующего занятия, на случай если у меня пять случится приступ деменции.
Задания сейчас проверю
