### ISSUE TITLE
Practice_FlyingButtons

### ISSUE THREAD

**Issue by smyilik** [smyilik/WASP_Homeworks#6]
@GalteXx 
Я вроде как сделал практику, но так-себе получилось, цвета только чёрный, белый и серый, и все кнопки находятся на прямой почему-то

**Comment by GalteXx** [comment]
Ты создаешь все random'ы одновременно => у них одинаковый сид. (по дефолту random при инициализации берет время пк).
Тогда при random.next() они выдают одинаковые значения. Создай один random и гоняй его постоянно. Или создавай Random локально в методах.
Вот так. Пока что засчитать не могу, переделаешь - получишь оба стингура.

**Comment by smyilik** [comment]
@GalteXx исправил
